### ISSUE TITLE
Line #5 in main.tf tagsnot expected here

### ISSUE THREAD

**Issue by devops-cinch** [felipefrizzo/terraform-aws-transfer-server#4]
Locally I ended up commenting out the tags line

Error: Unsupported block type
on .terraform/modules/transfer-server/terraform-aws-transfer-server-0.0.4/main.tf line 5, in resource "aws_transfer_server" "transfer_server":
   5:   tags {
Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

**Comment by felipefrizzo** [comment]
Thank you for your bug report, problem fixed.
