### ISSUE TITLE
tag issue does not seem to be pulling down 

### ISSUE THREAD

**Issue by vsem-cinch** [felipefrizzo/terraform-aws-transfer-server#5]
Greetings! I see that you have fixed the tag issue. However, when I tried to used the module it's still pulling down the old code. This is what I'm using
module "sftp-server" {
  source  = "felipefrizzo/transfer-server/aws"
  version = "0.0.4"

Thanks!

**Comment by felipefrizzo** [comment]
Hey, try to use version `0.0.5` or if the problem persists try to use source from GitHub like that:   

```hcl
module "sftp-server" {
  source = "git::https://github.com:felipefrizzo/terraform-aws-transfer-server.git?ref=master"
  ...
```

Regards.

**Comment by vsem-cinch** [comment]
Okay will do! Thx!
